
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SONY
 */
public class ForgotPassword extends javax.swing.JFrame {

	/**
	 * Creates new form ForgotPassword
	 */
	String ip, userid, vc1;

	public ForgotPassword(String ip, String userid, String vc) {
		super("My Chat Application::Forgot Password");
		initComponents();
		setSize(800, 700);
		setLocationRelativeTo(null);
		this.ip = ip;
		this.userid = userid;
		vc1 = vc;
		jTextField1.setText(userid);
		setResizable(false);
		try {
			BufferedImage img = ImageIO.read(getClass().getResourceAsStream("logo.jpg"));
			setIconImage(img);
		} catch (Exception e) {
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton2 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(null);

		jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton2.setText("BACK");
		jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton2);
		jButton2.setBounds(540, 420, 90, 40);
		getContentPane().add(jTextField3);
		jTextField3.setBounds(370, 320, 280, 30);

		jLabel7.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel7.setText("Verification Code");
		getContentPane().add(jLabel7);
		jLabel7.setBounds(160, 320, 179, 40);

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton1.setText("SUBMIT");
		jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton1);
		jButton1.setBounds(380, 420, 90, 40);

		jLabel4.setFont(new java.awt.Font("Vani", 1, 30)); // NOI18N
		jLabel4.setText("Verification");
		getContentPane().add(jLabel4);
		jLabel4.setBounds(310, 170, 200, 50);

		jLabel6.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel6.setText("User Id");
		getContentPane().add(jLabel6);
		jLabel6.setBounds(160, 270, 75, 40);

		jTextField1.setEditable(false);
		getContentPane().add(jTextField1);
		jTextField1.setBounds(370, 270, 280, 30);

		jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel9.setForeground(new java.awt.Color(204, 0, 0));
		jLabel9.setText("<html>&copy; copyright DEEPAK 2015</html>");
		getContentPane().add(jLabel9);
		jLabel9.setBounds(40, 580, 210, 30);

		jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
		jLabel3.setText("MY CHAT APPLICATION");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(170, 30, 460, 60);

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/580_400.jpg"))); // NOI18N
		jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		getContentPane().add(jLabel2);
		jLabel2.setBounds(100, 150, 580, 400);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/800_700.jpg"))); // NOI18N
		getContentPane().add(jLabel1);
		jLabel1.setBounds(0, 0, 800, 700);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		String vc = jTextField3.getText();
		if (!vc.trim().equals("")) {
			if (vc1.equals(vc)) {
				Toolkit.getDefaultToolkit().beep();
				JOptionPane.showMessageDialog(this, "Please Create your new password!!!");
				new ChangePassword(userid, ip, true).setVisible(true);
				this.dispose();
			} else {
				Toolkit.getDefaultToolkit().beep();
				JOptionPane.showMessageDialog(this, "Please enter correct Verification Code!!!");
				jTextField3.setText("");
				jTextField3.requestFocus();
			}
		} else {
			Toolkit.getDefaultToolkit().beep();
			JOptionPane.showMessageDialog(this, "Please Fill Verification Code!!!");
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		new Login().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				// new ForgotPassword().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables
}
