import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.rmi.Naming;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Signup extends javax.swing.JFrame {
	int n = 0, c = 0, sc = 0;
	String ip;
	JFrame f;
	boolean bo = true;

	public Signup(String ip) {
		super("My Chat Application::Signup Window");
		initComponents();
		setSize(800, 700);
		setLocationRelativeTo(null);
		this.ip = ip;
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			Connection con = DriverManager.getConnection("jdbc:oracle:thin:@" + ip + ":1521:XE", "system", "system");
			Statement st = con.createStatement();
			st.execute(
					"create table chat(name varchar2 (200),userid varchar2 (200),emailid varchar2 (200),mobile varchar2 (200),address varchar2 (200),password varchar2 (200),male varchar2 (200),high varchar2 (200),inter varchar2 (200),grad varchar2 (200),home "
							+ "varchar2 (200),city varchar2 (200),day varchar2 (200),month varchar2 (200),year varchar2 (200),"
							+ "lang varchar2 (200),imgname varchar2 (4000),tempid varchar2 (4000),verifystatus varchar2 (2))");
			BufferedImage img = ImageIO.read(getClass().getResourceAsStream("logo.jpg"));
			setIconImage(img);

		} catch (Exception e) {
			System.out.println(e);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jLabel2 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jPasswordField3 = new javax.swing.JPasswordField();
		jLabel10 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jPasswordField2 = new javax.swing.JPasswordField();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton1 = new javax.swing.JRadioButton();
		jComboBox4 = new javax.swing.JComboBox();
		jComboBox3 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		getContentPane().setLayout(null);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		getContentPane().add(jScrollPane2);
		jScrollPane2.setBounds(340, 390, 360, 70);

		jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel2.setForeground(new java.awt.Color(204, 0, 0));
		jLabel2.setText("<html>&copy; copyright DEEPAK 2015</html>");
		jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jLabel2MouseEntered(evt);
			}

			public void mouseExited(java.awt.event.MouseEvent evt) {
				jLabel2MouseExited(evt);
			}
		});
		getContentPane().add(jLabel2);
		jLabel2.setBounds(30, 630, 210, 30);

		jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton3.setText("SUBMIT");
		jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton3);
		jButton3.setBounds(360, 580, 110, 40);

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jButton1.setText("BACK");
		jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		getContentPane().add(jButton1);
		jButton1.setBounds(580, 580, 90, 40);
		getContentPane().add(jPasswordField3);
		jPasswordField3.setBounds(340, 520, 360, 30);

		jLabel10.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel10.setText("Confirm Password ");
		getContentPane().add(jLabel10);
		jLabel10.setBounds(100, 520, 210, 30);

		jLabel9.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel9.setText("Password ");
		getContentPane().add(jLabel9);
		jLabel9.setBounds(100, 480, 110, 30);

		jPasswordField2.setToolTipText("");
		getContentPane().add(jPasswordField2);
		jPasswordField2.setBounds(340, 480, 360, 30);

		jLabel5.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel5.setText("Address");
		getContentPane().add(jLabel5);
		jLabel5.setBounds(100, 420, 90, 40);

		jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				jTextField1KeyPressed(evt);
			}

			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField1KeyTyped(evt);
			}
		});
		getContentPane().add(jTextField1);
		jTextField1.setBounds(380, 350, 320, 30);

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jLabel14.setText("+91");
		getContentPane().add(jLabel14);
		jLabel14.setBounds(340, 350, 40, 30);

		buttonGroup1.add(jRadioButton2);
		jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jRadioButton2.setText("Female");
		getContentPane().add(jRadioButton2);
		jRadioButton2.setBounds(440, 300, 70, 23);

		buttonGroup1.add(jRadioButton1);
		jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jRadioButton1.setSelected(true);
		jRadioButton1.setText("Male");
		getContentPane().add(jRadioButton1);
		jRadioButton1.setBounds(320, 300, 60, 23);

		jComboBox4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "1999", "1998", "1997", "1996",
				"1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983",
				"1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970",
				"1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957",
				"1956", "1955", "1954", "1953", "1952", "1951", " " }));
		jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jComboBox4.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jComboBox4FocusGained(evt);
			}
		});
		getContentPane().add(jComboBox4);
		jComboBox4.setBounds(620, 250, 70, 30);

		jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "JAN", "FEB", "MAR", "APR",
				"MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
		jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jComboBox3.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jComboBox3FocusGained(evt);
			}
		});
		getContentPane().add(jComboBox3);
		jComboBox3.setBounds(470, 250, 80, 30);

		jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "01", "02", "03", "04", "05",
				"06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22",
				"23", "24", "25", "26", "27", "28", "29", "30", "31" }));
		jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jComboBox2.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jComboBox2FocusGained(evt);
			}
		});
		getContentPane().add(jComboBox2);
		jComboBox2.setBounds(320, 250, 70, 30);

		jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField3KeyTyped(evt);
			}
		});
		getContentPane().add(jTextField3);
		jTextField3.setBounds(320, 200, 370, 30);

		jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField4KeyTyped(evt);
			}
		});
		getContentPane().add(jTextField4);
		jTextField4.setBounds(320, 160, 370, 30);

		jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField2KeyTyped(evt);
			}
		});
		getContentPane().add(jTextField2);
		jTextField2.setBounds(320, 120, 370, 30);

		jLabel6.setFont(new java.awt.Font("Vani", 1, 30)); // NOI18N
		jLabel6.setText("Signup ");
		getContentPane().add(jLabel6);
		jLabel6.setBounds(350, 60, 130, 40);

		jLabel13.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel13.setText("Name");
		getContentPane().add(jLabel13);
		jLabel13.setBounds(100, 120, 80, 30);

		jLabel7.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel7.setText("User ID ");
		getContentPane().add(jLabel7);
		jLabel7.setBounds(100, 160, 90, 30);

		jLabel8.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel8.setText("Email ID ");
		getContentPane().add(jLabel8);
		jLabel8.setBounds(100, 210, 100, 30);

		jLabel12.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel12.setText("Date Of Birth");
		getContentPane().add(jLabel12);
		jLabel12.setBounds(100, 260, 180, 30);

		jLabel11.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel11.setText("Gender");
		getContentPane().add(jLabel11);
		jLabel11.setBounds(100, 300, 100, 30);

		jLabel3.setFont(new java.awt.Font("Vani", 1, 20)); // NOI18N
		jLabel3.setText("Mobile");
		getContentPane().add(jLabel3);
		jLabel3.setBounds(100, 350, 80, 30);

		jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
		jLabel1.setText("MY CHAT APPLICATION");
		getContentPane().add(jLabel1);
		jLabel1.setBounds(170, 10, 470, 40);

		jLabel16.setFont(new java.awt.Font("Vani", 1, 30)); // NOI18N
		jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/690_600.jpg"))); // NOI18N
		jLabel16.setToolTipText("");
		jLabel16.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		getContentPane().add(jLabel16);
		jLabel16.setBounds(60, 50, 690, 580);

		jLabel15.setFont(new java.awt.Font("Vani", 1, 30)); // NOI18N
		jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/800_700.jpg"))); // NOI18N
		getContentPane().add(jLabel15);
		jLabel15.setBounds(0, 0, 800, 700);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		String s6 = jPasswordField3.getText();
		String s5 = jPasswordField2.getText();
		String s2 = jTextField2.getText();
		String s1 = jTextField1.getText();
		String s7 = jTextArea2.getText();
		int len = s1.length();
		String s3 = jTextField3.getText();
		String s4 = jTextField4.getText();
		Object obj2 = jComboBox2.getSelectedItem();
		Object obj3 = jComboBox3.getSelectedItem();
		Object obj4 = jComboBox4.getSelectedItem();
		ButtonModel model = jRadioButton1.getModel();
		boolean equals = buttonGroup1.getSelection().equals(model);
		if (!(s1.trim().equals("") || s2.trim().equals("") || s3.trim().equals("") || s4.trim().equals("")
				|| s5.trim().equals("") || s6.trim().equals("") || s7.trim().equals("") || obj2.equals("Date")
				|| obj3.equals("Month") || obj4.equals("Year"))) {
			if (s6.equals(s5)) {
				if (!((!s3.startsWith("@")) && (s3.contains(".")) && (s3.contains("@")))) {
					Toolkit.getDefaultToolkit().beep();
					JOptionPane.showMessageDialog(this, "Please Enter A Full Email ID!!!");
					jTextField3.requestFocus(true);
					jTextField3.setText("");
				} else if (len < 10) {
					Toolkit.getDefaultToolkit().beep();
					JOptionPane.showMessageDialog(this, "Please Enter A Valid Mobile Number!!!");
					jTextField1.requestFocus(true);
					jTextField1.setText("");
				} else {
					try {
						ServerInterface ser = (ServerInterface) Naming.lookup("rmi://" + ip + "/chat");
						bo = ser.log(s4);
						// System.out.print("bo="+bo);
						if (bo) {
							Toolkit.getDefaultToolkit().beep();
							JOptionPane.showMessageDialog(this, "Please Try With Another USERID!!!");
							jTextField4.setText("");
							jTextField4.requestFocus();
						} else {
							String sendMail = ser.sendMail(s3, "hi");
							boolean allEmail = ser.getAllEmail(s3);
							if (allEmail) {
								Toolkit.getDefaultToolkit().beep();
								JOptionPane.showMessageDialog(this, "Please Try with another Email ID!!!");
								jTextField3.setText("");
							} else {
								if (sendMail.equals("enter your userid")) {
									Toolkit.getDefaultToolkit().beep();
									JOptionPane.showMessageDialog(this, "Please Enter A Valid Email ID!!!");
								} else if (sendMail.equals("try again later")) {
									Toolkit.getDefaultToolkit().beep();
									JOptionPane.showMessageDialog(this, "Please Try Again Later!!!");
								} else {
									ser.signup(s2, s4, s3, s1, s7, s5, obj2, obj3, obj4, equals);
									Toolkit.getDefaultToolkit().beep();
									JOptionPane.showMessageDialog(this,
											"Signup Successfull\n An Email has been sent to your emailid " + s3
													+ " ,\nYou have To verify Your EmailId by clicking the given link!!!");
									new Login().setVisible(true);
									this.dispose();
								}
							}
						}
					} catch (Exception e) {
						Toolkit.getDefaultToolkit().beep();
						JOptionPane.showMessageDialog(this, "Wrong IP Address!!!");
					}
				}

			} else {
				Toolkit.getDefaultToolkit().beep();
				JOptionPane.showMessageDialog(this, "Please Confirm The Password Correctly!!!");
				jPasswordField3.requestFocus(true);
				jPasswordField3.setText("");
			}
		} else {
			Toolkit.getDefaultToolkit().beep();
			JOptionPane.showMessageDialog(this, "Please Fill The Blank Field(s)!!!");
		}

	}// GEN-LAST:event_jButton3ActionPerformed

	private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField2KeyTyped
		char ch = evt.getKeyChar();
		if (!((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') || ch == java.awt.event.KeyEvent.VK_BACK_SPACE
				|| ch == java.awt.event.KeyEvent.VK_SPACE || ch == java.awt.event.KeyEvent.VK_DELETE)) {
			evt.consume();
			Toolkit.getDefaultToolkit().beep();
		}

	}// GEN-LAST:event_jTextField2KeyTyped

	private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseEntered
		jLabel2.setText("<html>&copy; copyright DEEPAK 2014</html>");
	}// GEN-LAST:event_jLabel2MouseEntered

	private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MouseExited
		jLabel2.setText("<html>&copy; copyright DEEPAK 2014</html>");
	}// GEN-LAST:event_jLabel2MouseExited

	private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyTyped
		String s = jTextField1.getText();
		int len = s.length();
		char ch = evt.getKeyChar();
		if (!(ch >= '0' && ch <= '9') || ch == java.awt.event.KeyEvent.VK_BACK_SPACE
				|| ch == java.awt.event.KeyEvent.VK_DELETE) {
			evt.consume();
		}
		if (len >= 10) {
			evt.consume();
			Toolkit.getDefaultToolkit().beep();
		}
	}// GEN-LAST:event_jTextField1KeyTyped

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		new Login().setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyPressed
		int keycode = evt.getKeyCode();
		if (keycode == KeyEvent.VK_BACK_SPACE || keycode == KeyEvent.VK_DELETE) {
		}
	}// GEN-LAST:event_jTextField1KeyPressed

	private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField3KeyTyped
		char ch = evt.getKeyChar();
		if (!((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9')
				|| ch == java.awt.event.KeyEvent.VK_PERIOD || ch == '@' || ch == java.awt.event.KeyEvent.VK_BACK_SPACE
				|| ch == java.awt.event.KeyEvent.VK_DELETE)) {
			evt.consume();
		}
	}// GEN-LAST:event_jTextField3KeyTyped

	private void jComboBox3FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jComboBox3FocusGained
		String s1 = jComboBox2.getSelectedItem().toString();
		String s4 = jComboBox4.getSelectedItem().toString();
		if (s1.equals("30")) {
			jComboBox3.removeAllItems();
			jComboBox3.addItem("Month");
			jComboBox3.addItem("JAN");
			jComboBox3.addItem("MAR");
			jComboBox3.addItem("APR");
			jComboBox3.addItem("MAY");
			jComboBox3.addItem("JUN");
			jComboBox3.addItem("JUL");
			jComboBox3.addItem("AUG");
			jComboBox3.addItem("SEP");
			jComboBox3.addItem("OCT");
			jComboBox3.addItem("NOV");
			jComboBox3.addItem("DEC");
		} else if (s1.equals("31")) {
			jComboBox3.removeAllItems();
			jComboBox3.addItem("Month");
			jComboBox3.addItem("JAN");
			jComboBox3.addItem("MAR");
			jComboBox3.addItem("MAY");
			jComboBox3.addItem("JUL");
			jComboBox3.addItem("AUG");
			jComboBox3.addItem("OCT");
			jComboBox3.addItem("DEC");
		}
		int t = 0;
		if (!s1.equals("Day"))
			t = Integer.parseInt(s1);
		if (t < 29 || s1.equals("Day")) {
			jComboBox3.removeAllItems();
			jComboBox3.addItem("Month");
			jComboBox3.addItem("JAN");
			jComboBox3.addItem("FEB");
			jComboBox3.addItem("MAR");
			jComboBox3.addItem("APR");
			jComboBox3.addItem("MAY");
			jComboBox3.addItem("JUN");
			jComboBox3.addItem("JUL");
			jComboBox3.addItem("AUG");
			jComboBox3.addItem("SEP");
			jComboBox3.addItem("OCT");
			jComboBox3.addItem("NOV");
			jComboBox3.addItem("DEC");
		}
		if (((s4.equals("Year")) || (s4.equals("1996")) || (s4.equals("1992")) || (s4.equals("1988"))
				|| (s4.equals("1984")) || (s4.equals("1980")) || (s4.equals("1976")) || (s4.equals("1972"))
				|| (s4.equals("1968")) || (s4.equals("1964")) || (s4.equals("1960")) || (s4.equals("1956"))
				|| (s4.equals("1952")))) {

			if (t > 29) {
				jComboBox3.removeAllItems();
				jComboBox3.addItem("Month");
				jComboBox3.addItem("JAN");
				jComboBox3.addItem("MAR");
				jComboBox3.addItem("APR");
				jComboBox3.addItem("MAY");
				jComboBox3.addItem("JUN");
				jComboBox3.addItem("JUL");
				jComboBox3.addItem("AUG");
				jComboBox3.addItem("SEP");
				jComboBox3.addItem("OCT");
				jComboBox3.addItem("NOV");
				jComboBox3.addItem("DEC");
			}
		}
		if (s1.equals("29")) {
			if (((s4.equals("Year")) || (s4.equals("1996")) || (s4.equals("1992")) || (s4.equals("1988"))
					|| (s4.equals("1984")) || (s4.equals("1980")) || (s4.equals("1976")) || (s4.equals("1972"))
					|| (s4.equals("1968")) || (s4.equals("1964")) || (s4.equals("1960")) || (s4.equals("1956"))
					|| (s4.equals("1952")))) {
				jComboBox3.removeAllItems();
				jComboBox3.addItem("Month");
				jComboBox3.addItem("JAN");
				jComboBox3.addItem("FEB");
				jComboBox3.addItem("MAR");
				jComboBox3.addItem("APR");
				jComboBox3.addItem("MAY");
				jComboBox3.addItem("JUN");
				jComboBox3.addItem("JUL");
				jComboBox3.addItem("AUG");
				jComboBox3.addItem("SEP");
				jComboBox3.addItem("OCT");
				jComboBox3.addItem("NOV");
				jComboBox3.addItem("DEC");
			}

			else {
				jComboBox3.removeAllItems();
				jComboBox3.addItem("Month");
				jComboBox3.addItem("JAN");
				jComboBox3.addItem("MAR");
				jComboBox3.addItem("APR");
				jComboBox3.addItem("MAY");
				jComboBox3.addItem("JUN");
				jComboBox3.addItem("JUL");
				jComboBox3.addItem("AUG");
				jComboBox3.addItem("SEP");
				jComboBox3.addItem("OCT");
				jComboBox3.addItem("NOV");
				jComboBox3.addItem("DEC");
			}
		}

	}// GEN-LAST:event_jComboBox3FocusGained

	private void jComboBox4FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jComboBox4FocusGained
		String s1 = jComboBox2.getSelectedItem().toString();
		String s2 = jComboBox3.getSelectedItem().toString();
		if (s1.equals("29") && s2.equals("FEB")) {
			jComboBox4.removeAllItems();
			jComboBox4.addItem("Year");
			for (int i = 96; i > 51; i = i - 4) {
				jComboBox4.addItem("19" + i);
			}
		} else {
			jComboBox4.removeAllItems();
			jComboBox4.addItem("Year");
			for (int i = 99; i >= 51; i--) {
				jComboBox4.addItem("19" + i);
			}
		}
	}// GEN-LAST:event_jComboBox4FocusGained

	boolean b = true;

	private void jComboBox2FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jComboBox2FocusGained
		String s3 = jComboBox3.getSelectedItem().toString();
		String s4 = jComboBox4.getSelectedItem().toString();
		if (s3.equals("FEB")) {
			if (((s4.equals("Year")) || (s4.equals("1996")) || (s4.equals("1992")) || (s4.equals("1988"))
					|| (s4.equals("1984")) || (s4.equals("1980")) || (s4.equals("1976")) || (s4.equals("1972"))
					|| (s4.equals("1968")) || (s4.equals("1964")) || (s4.equals("1960")) || (s4.equals("1956"))
					|| (s4.equals("1952")))) {
				jComboBox2.removeAllItems();
				jComboBox2.addItem("Day");
				for (int z = 1; z <= 9; z++)
					jComboBox2.addItem("0" + z);
				for (int z = 0; z <= 9; z++)
					jComboBox2.addItem("1" + z);
				for (int z = 0; z <= 9; z++)
					jComboBox2.addItem("2" + z);
			} else if (!(s4.equals("1996") && (s4.equals("1992")) && (s4.equals("1988")) && (s4.equals("1984"))
					&& (s4.equals("1980")) && (s4.equals("1976")) && (s4.equals("1972")) && (s4.equals("1968"))
					&& (s4.equals("1964")) && (s4.equals("1960")) && (s4.equals("1956")) && (s4.equals("1952")))) {
				jComboBox2.removeAllItems();
				jComboBox2.addItem("Day");
				for (int z = 1; z <= 9; z++)
					jComboBox2.addItem("0" + z);
				for (int z = 0; z <= 9; z++)
					jComboBox2.addItem("1" + z);
				for (int z = 0; z <= 8; z++)
					jComboBox2.addItem("2" + z);
			}

		} else if ((s3.equals("APR") || s3.equals("JUN") || s3.equals("SEP") || s3.equals("NOV"))) {
			jComboBox2.removeAllItems();
			jComboBox2.addItem("Day");
			for (int z = 1; z <= 9; z++)
				jComboBox2.addItem("0" + z);
			for (int z = 0; z <= 9; z++)
				jComboBox2.addItem("1" + z);
			for (int z = 0; z <= 9; z++)
				jComboBox2.addItem("2" + z);
			jComboBox2.addItem("30");
		} else {
			jComboBox2.removeAllItems();
			jComboBox2.addItem("Day");
			for (int z = 1; z <= 9; z++)
				jComboBox2.addItem("0" + z);
			for (int z = 0; z <= 9; z++)
				jComboBox2.addItem("1" + z);
			for (int z = 0; z <= 9; z++)
				jComboBox2.addItem("2" + z);
			jComboBox2.addItem("30");
			jComboBox2.addItem("31");
		}

	}// GEN-LAST:event_jComboBox2FocusGained

	private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField4KeyTyped
		char ch = evt.getKeyChar();
		if ((ch == java.awt.event.KeyEvent.VK_SPACE || ch == ':')) {
			evt.consume();
			Toolkit.getDefaultToolkit().beep();
		}
	}// GEN-LAST:event_jTextField4KeyTyped

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				// new Signup().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JComboBox jComboBox4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField3;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables
}
